# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: releaseo

before:
  hooks:
    - go mod tidy

builds:
  - id: releaseo
    binary: releaseo
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: releaseo
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: stacklok
    name: releaseo
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
