name: 'Releaseo'
description: 'Creates release PRs with version bumps for VERSION file and YAML files'
author: 'Stacklok'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  bump_type:
    description: 'Version bump type (major, minor, patch)'
    required: true
  version_file:
    description: 'Path to VERSION file'
    required: false
    default: 'VERSION'
  helm_docs_args:
    description: 'Arguments to pass to helm-docs. If provided, helm-docs will run with these args (e.g., --chart-search-root=./charts --template-files=README.md.gotmpl)'
    required: false
    default: ''
  version_files:
    description: |
      YAML list of files with custom version paths to update.
      Each entry should have: file (path), path (YAML node path), and optionally prefix.
      Example:
        - file: deploy/charts/myapp/Chart.yaml
          path: version
        - file: deploy/charts/myapp/Chart.yaml
          path: appVersion
        - file: deploy/charts/myapp/values.yaml
          path: image.tag
          prefix: "v"
    required: false
    default: ''
  token:
    description: 'GitHub token for creating PR'
    required: true
  base_branch:
    description: 'Base branch for the PR'
    required: false
    default: 'main'

outputs:
  version:
    description: 'The new version number'
    value: ${{ steps.releaseo.outputs.version }}
  pr_number:
    description: 'The created PR number'
    value: ${{ steps.releaseo.outputs.pr_number }}
  pr_url:
    description: 'The created PR URL'
    value: ${{ steps.releaseo.outputs.pr_url }}

runs:
  using: 'composite'
  steps:
    - name: Run releaseo
      id: releaseo
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        VERSION_FILES_YAML: ${{ inputs.version_files }}
      run: |
        ARGS=(
          --bump-type="${{ inputs.bump_type }}"
          --version-file="${{ inputs.version_file }}"
          --base-branch="${{ inputs.base_branch }}"
        )

        if [ -n "${{ inputs.helm_docs_args }}" ]; then
          ARGS+=(--helm-docs-args="${{ inputs.helm_docs_args }}")
        fi

        if [ -n "$VERSION_FILES_YAML" ]; then
          VERSION_FILES_JSON=$(echo "$VERSION_FILES_YAML" | yq -o=json -I=0 '.')
          ARGS+=(--version-files="$VERSION_FILES_JSON")
        fi

        go run github.com/stacklok/releaseo@v1.0.7 "${ARGS[@]}"
